---
version: "3.2"

services:
  influxdb-test:
    container_name: influxdb-test
    image: influxdb:1.8
    ports:
      - 8086:8086
    expose:
      - 8086
    environment:
      - INFLUX_DB=deebee
