---
version: "3.2"

services:
  env-reporting-api:
    container_name: env-reporting-api
    build: .
    ports:
      - 3030:3030
    expose:
      - 3030
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_DB=deebee
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086
    expose:
      - 8086
    environment:
      - INFLUXDB_DB=deebee
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.1.2
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    expose:
      - 3000
volumes:
  influxdb-data:
  grafana-data:
